server:
  port: 8888

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE

resource-uri: http://localhost:8090
